# Generated by Django 6.0.7 on 2026-07-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
