# Generated by Django 6.0.7 on 2026-07-29 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=150)),
                ('paddy_type', models.CharField(max_length=50)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_lkr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_made', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'purchases',
                'indexes': [models.Index(fields=['warehouse', '-purchase_date'], name='purchases_warehou_5445a0_idx'), models.Index(fields=['payment_status'], name='purchases_payment_e600ce_idx'), models.Index(fields=['-purchase_date'], name='purchases_purchas_ec7745_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='ck_purchase_quantity_positive'), models.CheckConstraint(condition=models.Q(('amount_lkr__gte', 0)), name='ck_purchase_amount_non_negative')],
            },
        ),
    ]
