# Generated by Django 6.0.7 on 2026-07-29 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('district', models.CharField(db_index=True, max_length=80)),
                ('location', models.CharField(max_length=200)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_stock_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouses',
                'indexes': [models.Index(fields=['district', 'status'], name='warehouses_distric_80eed1_idx'), models.Index(fields=['-created_at'], name='warehouses_created_b3e92b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity_kg__gt', 0)), name='ck_warehouse_capacity_positive'), models.CheckConstraint(condition=models.Q(('current_stock_kg__gte', 0)), name='ck_warehouse_stock_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('paddy_type', models.CharField(max_length=50)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('storage_date', models.DateField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'inventory',
                'indexes': [models.Index(fields=['warehouse', '-storage_date'], name='inventory_warehou_9eba55_idx')],
            },
        ),
    ]
