# Generated by Django 6.0.7 on 2026-07-29 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['-created_at'], name='approvals_created_74969b_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['entity_type', 'entity_id'], name='approvals_entity__d57650_idx'),
        ),
    ]
